### ISSUE TITLE
Properties page crashes nautilus when viewing remote files

### ISSUE THREAD

**Issue by null-von-sushi** [talklittle/tmsu-nautilus-rs#26]
The probably relevant part of a log:
```
thread '<unnamed>' panicked at 'could not query tmsu tags: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
[1]    30703 abort (core dumped)  nautilus
```

This happens when opening the properties page on a server (using ssh).

**Comment by null-von-sushi** [comment]
Full log with RUST Backtrace enabled https://hastebin.com/ifucuwaxuq.coffeescript

**Comment by talklittle** [comment]
I can reproduce the bug. Thanks for reporting.

**Comment by talklittle** [comment]
Fixed in version 0.5.0: https://github.com/talklittle/tmsu-nautilus-rs/releases/tag/v0.5.0

**Comment by null-von-sushi** [comment]
No longer crashes, but TMSU tags show empty

**Comment by talklittle** [comment]
Does TMSU command line handle tags for those files? If so, can you show the command line syntax?

**Comment by null-von-sushi** [comment]
Yes?
I don't really use the command line for TMSU, but if open a terminal, I can navigate to the path on the server where the files are (gnome puts mounted things in a weird place..)
```$: cd /run/user/1000/gvfs/sftp:host=192.168.1.2/folder/on/my/server\ with\ spaces```
and then read the tags of the file
```
$: tmsu tags a\ file.abc
tag1      tag2        tag3      tag4        tag5
tag6      tag7        tag8      tag9            
```

**Comment by null-von-sushi** [comment]
Admittedly, I had some problems trying to set tags myself just now (tmsu compains about the database being read only despite it not being readonly), but that's an issue with TMSU itself and doesn't impact tag-reading ability

**Comment by talklittle** [comment]
Okay thanks for confirming. Opened issue #27

**Comment by null-von-sushi** [comment]
thanks
